name: Build & Publish Blazor WASM application

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: Version of dotnet to use
        type: string
        required: false
        default: 6.0.x
        
      project-folder:
        description: The folder containing the project to build
        type: string
        default: .
        
      restore-from-private-nuget:
        description: Restore from private nuget packages
        type: boolean
        default: false
        
      nuget-source:
        description: nuget registry source
        type: string
        required: false
        
    secrets:
      nuget-auth:
        description: GitHub PAT token
        required: false
      
      nuget-username:
        description: GitHub username
        required: false

jobs:
  build-solution:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      
      - name: Add private Nuget package source
        if: ${{inputs.restore-from-private-nuget}}
        run: dotnet nuget add source --username ${{ secrets.nuget-username }} --password ${{ secrets.nuget-auth }} --store-password-in-clear-text --name github ${{ inputs.nuget-source }}
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish --configuration Release -o ./published_app --no-build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ${{ inputs.project-folder }}/published_app/wwwroot
