name: Pack and publish package to GitHub packages

on: 
  workflow_call:
    inputs:
      version:
        description: verison to be set on the nuget package
        type: string
        required: true
        default: 1.0.0
      
      nuget-source:
        description: nuget registry source
        type: string
        required: true
              
      nuget-package_output_directory:
        description: output folder to publish the packed library
        type: string
        required: true
        
      dotnet-version:
        description: Version of dotnet to use
        type: string
        required: false
        default: 6.0.x
        
      project-folder:
        description: The folder containing the project to build
        type: string
        default: .
        
    secrets:
      nuget-auth:
        description: GitHub PAT token
        required: true
      
      nuget-username:
        description: GitHub username
        required: true
        
        
       
jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Add to Nuget Registry Source
        run: dotnet nuget add source --username ${{ secrets.nuget-username }} --password ${{ secrets.nuget-auth }} --store-password-in-clear-text --name github ${{ inputs.nuget-source }}

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --include-symbols -p:PackageVersion=${{ inputs.version }} --output ${{ inputs.nuget-package_output_directory }}

      - name: Publish Package
        run: dotnet nuget push ${{ inputs.nuget-package_output_directory }}/*.nupkg  --api-key ${{ secrets.nuget-auth }} --source "github" --skip-duplicate
      
    
       
      
      
